export const GET_USERS = 'GET_USERS';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_AUTHEDUSER = 'GET_AUTHEDUSER';
export const REMOVE_AUTHEDUSER = 'REMOVE_AUTHEDUSER';
export const SELECT_ANSWERED = 'SELECT_ANSWERED';
export const SELECT_UNANSWERED = 'SELECT_UNANSWERED';